<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>True</IsPackable>
    <DefineConstants>$(DefineConstants);RESHARPER</DefineConstants>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExtendedNumerics.BigDecimal" Version="3003.0.0.346" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageReference Include="JetBrains.ReSharper.SDK" Version="2026.1.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageReference Update="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\dependencies.json" PackagePath="" Pack="true" Visible="false" />
    <Content Include="bin\$(AssemblyName)\$(Configuration)\$(AssemblyName).dll" PackagePath="dotFiles" Pack="true" Visible="false" />
    <Content Include="bin\$(AssemblyName)\$(Configuration)\$(AssemblyName).pdb" PackagePath="dotFiles" Pack="true" Visible="false" />

    <!-- TODO: add additional assemblies -->
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Language\Base\Implementations\Flexible\Concretely\" />
    <Folder Include="Language\Base\Implementations\Flexible\Concretely\InternalNodes\Replacement\" />
    <Folder Include="Language\Base\Implementations\Flexible\Loose\Internal\Replacement\" />
    <Folder Include="Language\Leaf\Parser\Tree\Base\" />
    <Folder Include="Language\ObjectiveCXX\Parser\Tree\Base\" />
    <Folder Include="Language\ObjectiveC\Parser\Tree\Base\" />
    <Folder Include="Language\Swift\" />
    <Folder Include="Language\Swift\Parser\Tree\Expressions\PostfixExpressions\PrimaryExpressions\Literals\Literals\StringLiteral\InterpolatableStringLiterals\MultiLine\" />
    <Folder Include="Language\Swift\Parser\Tree\Expressions\PostfixExpressions\PrimaryExpressions\Literals\Literals\StringLiteral\RawValueStringLiterals\MultiLine\" />
    <Folder Include="Ressources\Icons\Language\Raw\Declarations\Swift\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Language\Swift\ProjectModel\SwiftPackageManager\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Language\Swift\ProjectModel\SwiftPackageManager\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Language\Swift\ProjectModel\SwiftPackageManager\**" />
  </ItemGroup>

</Project>
