<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>True</IsPackable>
    <DefineConstants>$(DefineConstants);RESHARPER</DefineConstants>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExtendedNumerics.BigDecimal" Version="3001.1.0.233" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageReference Include="JetBrains.ReSharper.SDK" Version="2025.3.0.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\dependencies.json" PackagePath="" Pack="true" Visible="false" />
    <Content Include="bin\$(AssemblyName)\$(Configuration)\$(AssemblyName).dll" PackagePath="dotFiles" Pack="true" Visible="false" />
    <Content Include="bin\$(AssemblyName)\$(Configuration)\$(AssemblyName).pdb" PackagePath="dotFiles" Pack="true" Visible="false" />

    <!-- TODO: add additional assemblies -->
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Language\Base\Implementations\Constrained\Concretely\" />
    <Folder Include="Language\Base\Implementations\Constrained\Loose\Internal\" />
    <Folder Include="Language\Base\Implementations\Constrained\Loose\Leaf\" />
    <Folder Include="Language\Base\Implementations\Constrained\Loose\Root\" />
    <Folder Include="Language\Base\Implementations\Flexible\Concretely\" />
    <Folder Include="Language\Base\Implementations\Flexible\Concretely\InternalNodes\Appending\" />
    <Folder Include="Language\Base\Implementations\Flexible\Concretely\InternalNodes\Contains\" />
    <Folder Include="Language\Base\Implementations\Flexible\Concretely\InternalNodes\Count\" />
    <Folder Include="Language\Base\Implementations\Flexible\Concretely\InternalNodes\Prepending\" />
    <Folder Include="Language\Base\Implementations\Flexible\Loose\Leaf\" />
    <Folder Include="Language\Base\Implementations\Flexible\Loose\Root\" />
    <Folder Include="Language\DooC\" />
    <Folder Include="Language\ModuleMaps\" />
    <Folder Include="Language\ObjectiveCPP\" />
    <Folder Include="Language\ObjectiveC\" />
    <Folder Include="Language\Swift\" />
    <Folder Include="Language\Swift\Parser\Tree\Base\Implementations\LeafNode\" />
    <Folder Include="Language\Swift\Parser\Tree\Base\Implementations\Root\" />
    <Folder Include="Ressources\Icons\Language\Raw\Declarations\Swift\" />
  </ItemGroup>

</Project>
