<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>ReSharperPlugin.Swift.Rider</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <IsPackable>false</IsPackable>
    <DefineConstants>$(DefineConstants);RIDER</DefineConstants>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExtendedNumerics.BigDecimal" Version="3001.1.0.233" />
    <PackageReference Include="IndexRange" Version="1.1.0" />
    <PackageReference Include="JetBrains.Rider.SDK" Version="2025.3.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="ReSharperPlugin.Swift.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Language\Parser\Tree\Statements\ControlTransferStatements\CompositeStatements\LoopControlTransferStatements\Breaks\" />
    <Folder Include="Language\Parser\Tree\Statements\LoopStatements\WhileLoops\" />
  </ItemGroup>

</Project>
