<Project>

  <PropertyGroup>
    <!-- See https://www.nuget.org/packages/JetBrains.ReSharper.SDK -->
    <!-- Keep in sync with ProductVersion in gradle.properties -->
    <SdkVersion>2026.2.0</SdkVersion>

    <Title>SO++</Title>
    <Description>SoftOmni's RD-based support package for the Swift ecosystem</Description>

    <Authors>Author</Authors>
    <Copyright>Copyright $([System.DateTime]::Now.Year) Maintainers of Swift</Copyright>
    <PackageTags>resharper plugin</PackageTags>

    <PackageProjectUrl></PackageProjectUrl>
    <PackageLicenseUrl></PackageLicenseUrl>
    <PackageIconUrl></PackageIconUrl>
  </PropertyGroup>

</Project>
