<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>SoftOmni.SwiftRd.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GitHubActionsTestLogger" Version="3.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="JetBrains.ReSharper.SDK.Tests" Version="2026.2.0-eap08">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Update="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReSharperPlugin.Swift\ReSharperPlugin.Swift.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="test/**/*" />
    <Compile Include="test\Registration\SwiftLanguageTests.cs" />
    <Compile Include="test\Registration\SwiftProjectFileTypeTests.cs" />
    <None Include="test/**/*" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="test\data\scratch_testing\" />
  </ItemGroup>

</Project>
